[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DFW_VERSION_MAJOR=0
    -DFW_VERSION_MINOR=6
    -DFW_VERSION_PATCH=0
